# -*- coding: utf-8 -*-
"""pythonPLP_week7_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dh-sRd3va8yG57xlScW8Zs3kd_O0WTcy
"""

# Install required libraries (only if not available)
!pip install pandas matplotlib seaborn scikit-learn

# Analyzing Data with Pandas and Visualizing Results with Matplotlib
# Assignment Solution

# ----------------------------
# Task 1: Load and Explore the Dataset
# ----------------------------

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

# Load the Iris dataset from sklearn
iris = load_iris(as_frame=True)
df = iris.frame   # converts it into a pandas DataFrame

# Display the first 5 rows
print("First 5 rows of the dataset:")
print(df.head())

# Check dataset info (structure, datatypes, missing values)
print("\nDataset Info:")
print(df.info())

# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# (Dataset has no missing values, so no cleaning needed)

# ----------------------------
# Task 2: Basic Data Analysis
# ----------------------------

# Compute basic statistics
print("\nBasic Statistics of Numerical Columns:")
print(df.describe())

# Group by species and compute mean of numerical columns
grouped_means = df.groupby("target").mean()
print("\nMean values grouped by species:")
print(grouped_means)

# Mapping target numbers to species names for readability
df['species'] = df['target'].map({0: "setosa", 1: "versicolor", 2: "virginica"})

# Example finding:
print("\nObservation:")
print("Virginica flowers generally have larger petal length and width compared to Setosa and Versicolor.")

# ----------------------------
# Task 3: Data Visualization
# ----------------------------

# 1. Line Chart - showing petal length trends across samples
plt.figure(figsize=(8,5))
plt.plot(df.index, df['petal length (cm)'], label="Petal Length")
plt.title("Line Chart of Petal Length across Samples")
plt.xlabel("Sample Index")
plt.ylabel("Petal Length (cm)")
plt.legend()
plt.show()

# 2. Bar Chart - average petal length per species
plt.figure(figsize=(8,5))
sns.barplot(x="species", y="petal length (cm)", data=df, estimator="mean")
plt.title("Average Petal Length per Species")
plt.xlabel("Species")
plt.ylabel("Average Petal Length (cm)")
plt.show()

# 3. Histogram - distribution of sepal length
plt.figure(figsize=(8,5))
plt.hist(df["sepal length (cm)"], bins=15, color="skyblue", edgecolor="black")
plt.title("Distribution of Sepal Length")
plt.xlabel("Sepal Length (cm)")
plt.ylabel("Frequency")
plt.show()

# 4. Scatter Plot - Sepal Length vs. Petal Length
plt.figure(figsize=(8,5))
sns.scatterplot(x="sepal length (cm)", y="petal length (cm)", hue="species", data=df)
plt.title("Scatter Plot of Sepal Length vs. Petal Length")
plt.xlabel("Sepal Length (cm)")
plt.ylabel("Petal Length (cm)")
plt.legend(title="Species")
plt.show()